name: CI

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout the repository code

      - name: Install Dependencies
        run: npm install  # Install dependencies defined in package.json

      - name: Run Tests
        run: npm test  # Run tests defined in package.json
